import mysql.connector
from mysql.connector import Error

def import_syscohada():
    """Importer le plan comptable SYSCOHADA Afrique de l'Ouest"""
    
    try:
        conn = mysql.connector.connect(
            host='localhost',
            user='bien',
            password='iug2026',
            database='boutique'
        )
        cursor = conn.cursor()
        
        # Plan comptable SYSCOHADA RÉVISÉ Afrique de l'Ouest
        comptes_syscohada = [
            # CLASSE 1 : RESSOURCES STABLES
            ('101', 'Capital social', 'PASSIF'),
            ('1011', 'Capital souscrit - non appelé', 'PASSIF'),
            ('1012', 'Capital souscrit - appelé, non versé', 'PASSIF'),
            ('1013', 'Capital souscrit - appelé, versé', 'PASSIF'),
            ('104', 'Primes liées au capital', 'PASSIF'),
            ('105', 'Écarts de réévaluation', 'PASSIF'),
            ('106', 'Réserves', 'PASSIF'),
            ('1061', 'Réserve légale', 'PASSIF'),
            ('1062', 'Réserves statutaires', 'PASSIF'),
            ('1063', 'Réserves réglementées', 'PASSIF'),
            ('1064', 'Autres réserves', 'PASSIF'),
            ('108', 'Compte de l\'exploitant', 'PASSIF'),
            ('109', 'Actionnaires, capital souscrit non appelé', 'PASSIF'),
            ('12', 'Résultat de l\'exercice', 'PASSIF'),
            ('120', 'Résultat de l\'exercice (bénéfice)', 'PASSIF'),
            ('129', 'Résultat de l\'exercice (perte)', 'PASSIF'),
            ('13', 'Subventions d\'investissement', 'PASSIF'),
            ('131', 'Subventions d\'équipement', 'PASSIF'),
            ('138', 'Autres subventions d\'investissement', 'PASSIF'),
            ('139', 'Subventions d\'investissement inscrites au compte de résultat', 'PASSIF'),
            ('14', 'Provisions réglementées', 'PASSIF'),
            ('141', 'Provisions pour amortissements dérogatoires', 'PASSIF'),
            ('142', 'Provisions pour plus-values en instance d\'imposition', 'PASSIF'),
            ('143', 'Provisions pour investissement', 'PASSIF'),
            ('145', 'Amortissements dérogatoires', 'PASSIF'),
            ('146', 'Provisions spéciales de réévaluation', 'PASSIF'),
            ('147', 'Plus-values réinvesties', 'PASSIF'),
            ('148', 'Autres provisions réglementées', 'PASSIF'),
            ('15', 'Provisions pour risques et charges', 'PASSIF'),
            ('151', 'Provisions pour risques', 'PASSIF'),
            ('152', 'Provisions pour charges', 'PASSIF'),
            ('16', 'Emprunts et dettes assimilées', 'PASSIF'),
            ('161', 'Emprunts obligataires', 'PASSIF'),
            ('162', 'Emprunts auprès des établissements de crédit', 'PASSIF'),
            ('163', 'Dettes rattachées à des participations', 'PASSIF'),
            ('164', 'Avances reçues', 'PASSIF'),
            ('165', 'Dépôts et cautionnements reçus', 'PASSIF'),
            ('166', 'Participation des salariés aux résultats', 'PASSIF'),
            ('167', 'Emprunts et dettes en devises', 'PASSIF'),
            ('168', 'Autres emprunts et dettes assimilées', 'PASSIF'),
            ('17', 'Dettes rattachées à des participations', 'PASSIF'),
            ('171', 'Dettes rattachées à des participations', 'PASSIF'),
            ('174', 'Dettes rattachées à des sociétés en participation', 'PASSIF'),
            ('178', 'Autres dettes rattachées', 'PASSIF'),
            ('18', 'Comptes de liaison des établissements', 'PASSIF'),
            ('181', 'Comptes de liaison des établissements', 'PASSIF'),
            
            # CLASSE 2 : IMMOBILISATIONS
            ('20', 'Immobilisations incorporelles', 'ACTIF'),
            ('201', 'Frais de développement', 'ACTIF'),
            ('202', 'Concessions, brevets, licences', 'ACTIF'),
            ('203', 'Fonds commercial', 'ACTIF'),
            ('205', 'Investissements de création', 'ACTIF'),
            ('206', 'Logiciels', 'ACTIF'),
            ('207', 'Immobilisations incorporelles en cours', 'ACTIF'),
            ('208', 'Autres immobilisations incorporelles', 'ACTIF'),
            ('21', 'Immobilisations corporelles', 'ACTIF'),
            ('211', 'Terrains', 'ACTIF'),
            ('212', 'Agencements et aménagements de terrains', 'ACTIF'),
            ('213', 'Constructions', 'ACTIF'),
            ('214', 'Bâtiments', 'ACTIF'),
            ('215', 'Matériel et outillage', 'ACTIF'),
            ('216', 'Matériel industriel', 'ACTIF'),
            ('217', 'Matériel de transport', 'ACTIF'),
            ('218', 'Matériel de bureau et informatique', 'ACTIF'),
            ('219', 'Autres immobilisations corporelles', 'ACTIF'),
            ('22', 'Immobilisations en cours', 'ACTIF'),
            ('221', 'Immobilisations corporelles en cours', 'ACTIF'),
            ('222', 'Immobilisations incorporelles en cours', 'ACTIF'),
            ('23', 'Immobilisations financières', 'ACTIF'),
            ('231', 'Participations dans des entreprises liées', 'ACTIF'),
            ('232', 'Participations dans des entreprises liées', 'ACTIF'),
            ('233', 'Participations dans des entreprises liées', 'ACTIF'),
            ('234', 'Participations dans des entreprises liées', 'ACTIF'),
            ('235', 'Participations dans des entreprises liées', 'ACTIF'),
            ('236', 'Autres participations', 'ACTIF'),
            ('237', 'Autres immobilisations financières', 'ACTIF'),
            ('238', 'Créances rattachées à des participations', 'ACTIF'),
            ('239', 'Versements représentatifs d\'immobilisations', 'ACTIF'),
            ('24', 'Prêts', 'ACTIF'),
            ('241', 'Prêts aux associés', 'ACTIF'),
            ('242', 'Prêts au personnel', 'ACTIF'),
            ('243', 'Prêts aux entreprises liées', 'ACTIF'),
            ('244', 'Prêts aux entreprises liées', 'ACTIF'),
            ('245', 'Prêts aux entreprises liées', 'ACTIF'),
            ('246', 'Prêts aux entreprises liées', 'ACTIF'),
            ('247', 'Prêts aux entreprises liées', 'ACTIF'),
            ('248', 'Autres prêts', 'ACTIF'),
            ('25', 'Participations', 'ACTIF'),
            ('251', 'Titres de participation', 'ACTIF'),
            ('252', 'Actions propres', 'ACTIF'),
            ('253', 'Autres titres conférant un droit de propriété', 'ACTIF'),
            ('254', 'Titres participatifs', 'ACTIF'),
            ('255', 'Obligations', 'ACTIF'),
            ('256', 'Autres immobilisations financières', 'ACTIF'),
            ('26', 'Autres immobilisations financières', 'ACTIF'),
            ('261', 'Titres immobilisés autres que les participations', 'ACTIF'),
            ('262', 'Prêts', 'ACTIF'),
            ('263', 'Dépôts et cautionnements', 'ACTIF'),
            ('264', 'Intérêts courus', 'ACTIF'),
            ('265', 'Autres immobilisations financières', 'ACTIF'),
            ('27', 'Autres immobilisations financières', 'ACTIF'),
            ('271', 'Immobilisations corporelles en cours', 'ACTIF'),
            ('272', 'Immobilisations incorporelles en cours', 'ACTIF'),
            ('273', 'Immobilisations financières en cours', 'ACTIF'),
            ('274', 'Immobilisations en cours', 'ACTIF'),
            ('275', 'Immobilisations en cours', 'ACTIF'),
            ('276', 'Immobilisations en cours', 'ACTIF'),
            ('277', 'Immobilisations en cours', 'ACTIF'),
            ('278', 'Immobilisations en cours', 'ACTIF'),
            ('279', 'Immobilisations en cours', 'ACTIF'),
            ('28', 'Amortissements des immobilisations', 'ACTIF'),
            ('281', 'Amortissements des immobilisations incorporelles', 'ACTIF'),
            ('282', 'Amortissements des immobilisations corporelles', 'ACTIF'),
            ('283', 'Amortissements des immobilisations en cours', 'ACTIF'),
            ('284', 'Amortissements des immobilisations financières', 'ACTIF'),
            ('285', 'Amortissements des immobilisations en cours', 'ACTIF'),
            ('286', 'Amortissements des immobilisations en cours', 'ACTIF'),
            ('287', 'Amortissements des immobilisations en cours', 'ACTIF'),
            ('288', 'Amortissements des immobilisations en cours', 'ACTIF'),
            ('289', 'Amortissements des immobilisations en cours', 'ACTIF'),
            ('29', 'Provisions pour dépréciation des immobilisations', 'ACTIF'),
            ('291', 'Provisions pour dépréciation des immobilisations incorporelles', 'ACTIF'),
            ('292', 'Provisions pour dépréciation des immobilisations corporelles', 'ACTIF'),
            ('293', 'Provisions pour dépréciation des immobilisations en cours', 'ACTIF'),
            ('294', 'Provisions pour dépréciation des immobilisations financières', 'ACTIF'),
            ('295', 'Provisions pour dépréciation des immobilisations en cours', 'ACTIF'),
            ('296', 'Provisions pour dépréciation des immobilisations en cours', 'ACTIF'),
            ('297', 'Provisions pour dépréciation des immobilisations en cours', 'ACTIF'),
            ('298', 'Provisions pour dépréciation des immobilisations en cours', 'ACTIF'),
            ('299', 'Provisions pour dépréciation des immobilisations en cours', 'ACTIF'),
            
            # CLASSE 3 : STOCKS
            ('30', 'Stocks de marchandises', 'ACTIF'),
            ('301', 'Stocks de marchandises', 'ACTIF'),
            ('302', 'Stocks de matières premières', 'ACTIF'),
            ('303', 'Stocks de fournitures', 'ACTIF'),
            ('304', 'Stocks de produits en cours', 'ACTIF'),
            ('305', 'Stocks de produits finis', 'ACTIF'),
            ('306', 'Stocks de produits résiduels', 'ACTIF'),
            ('307', 'Stocks en cours de route', 'ACTIF'),
            ('308', 'Stocks à l\'extérieur', 'ACTIF'),
            ('309', 'Provisions pour dépréciation des stocks', 'ACTIF'),
            ('31', 'Matières premières et fournitures', 'ACTIF'),
            ('311', 'Matières premières', 'ACTIF'),
            ('312', 'Matières consommables', 'ACTIF'),
            ('313', 'Emballages', 'ACTIF'),
            ('314', 'Fournitures de bureau', 'ACTIF'),
            ('315', 'Fournitures d\'entretien', 'ACTIF'),
            ('316', 'Petits outillages', 'ACTIF'),
            ('317', 'Fournitures de magasin', 'ACTIF'),
            ('318', 'Autres fournitures', 'ACTIF'),
            ('319', 'Provisions pour dépréciation des matières premières', 'ACTIF'),
            ('32', 'Autres approvisionnements', 'ACTIF'),
            ('321', 'Matières consommables', 'ACTIF'),
            ('322', 'Fournitures consommables', 'ACTIF'),
            ('323', 'Combustibles', 'ACTIF'),
            ('324', 'Produits d\'entretien', 'ACTIF'),
            ('325', 'Fournitures d\'atelier', 'ACTIF'),
            ('326', 'Fournitures de bureau', 'ACTIF'),
            ('327', 'Fournitures de magasin', 'ACTIF'),
            ('328', 'Autres approvisionnements', 'ACTIF'),
            ('329', 'Provisions pour dépréciation des approvisionnements', 'ACTIF'),
            ('33', 'En-cours de production', 'ACTIF'),
            ('331', 'Produits en cours', 'ACTIF'),
            ('332', 'Travaux en cours', 'ACTIF'),
            ('333', 'Services en cours', 'ACTIF'),
            ('334', 'En-cours de production', 'ACTIF'),
            ('335', 'En-cours de production', 'ACTIF'),
            ('336', 'En-cours de production', 'ACTIF'),
            ('337', 'En-cours de production', 'ACTIF'),
            ('338', 'En-cours de production', 'ACTIF'),
            ('339', 'Provisions pour dépréciation des en-cours', 'ACTIF'),
            ('34', 'Produits intermédiaires et finis', 'ACTIF'),
            ('341', 'Produits intermédiaires', 'ACTIF'),
            ('342', 'Produits finis', 'ACTIF'),
            ('343', 'Produits résiduels', 'ACTIF'),
            ('344', 'Produits en cours', 'ACTIF'),
            ('345', 'Produits en cours', 'ACTIF'),
            ('346', 'Produits en cours', 'ACTIF'),
            ('347', 'Produits en cours', 'ACTIF'),
            ('348', 'Produits en cours', 'ACTIF'),
            ('349', 'Provisions pour dépréciation des produits', 'ACTIF'),
            ('35', 'Produits résiduels', 'ACTIF'),
            ('351', 'Déchets', 'ACTIF'),
            ('352', 'Rebuts', 'ACTIF'),
            ('353', 'Matières de récupération', 'ACTIF'),
            ('354', 'Produits résiduels', 'ACTIF'),
            ('355', 'Produits résiduels', 'ACTIF'),
            ('356', 'Produits résiduels', 'ACTIF'),
            ('357', 'Produits résiduels', 'ACTIF'),
            ('358', 'Produits résiduels', 'ACTIF'),
            ('359', 'Provisions pour dépréciation des produits résiduels', 'ACTIF'),
            ('36', 'Stocks en cours de route', 'ACTIF'),
            ('361', 'Stocks en cours de route', 'ACTIF'),
            ('362', 'Stocks en cours de route', 'ACTIF'),
            ('363', 'Stocks en cours de route', 'ACTIF'),
            ('364', 'Stocks en cours de route', 'ACTIF'),
            ('365', 'Stocks en cours de route', 'ACTIF'),
            ('366', 'Stocks en cours de route', 'ACTIF'),
            ('367', 'Stocks en cours de route', 'ACTIF'),
            ('368', 'Stocks en cours de route', 'ACTIF'),
            ('369', 'Provisions pour dépréciation des stocks en cours', 'ACTIF'),
            ('37', 'Stocks à l\'extérieur', 'ACTIF'),
            ('371', 'Stocks chez les clients', 'ACTIF'),
            ('372', 'Stocks en dépôt', 'ACTIF'),
            ('373', 'Stocks en consignation', 'ACTIF'),
            ('374', 'Stocks à l\'extérieur', 'ACTIF'),
            ('375', 'Stocks à l\'extérieur', 'ACTIF'),
            ('376', 'Stocks à l\'extérieur', 'ACTIF'),
            ('377', 'Stocks à l\'extérieur', 'ACTIF'),
            ('378', 'Stocks à l\'extérieur', 'ACTIF'),
            ('379', 'Provisions pour dépréciation des stocks extérieurs', 'ACTIF'),
            ('39', 'Provisions pour dépréciation des stocks', 'ACTIF'),
            ('391', 'Provisions pour dépréciation des marchandises', 'ACTIF'),
            ('392', 'Provisions pour dépréciation des matières premières', 'ACTIF'),
            ('393', 'Provisions pour dépréciation des approvisionnements', 'ACTIF'),
            ('394', 'Provisions pour dépréciation des en-cours', 'ACTIF'),
            ('395', 'Provisions pour dépréciation des produits finis', 'ACTIF'),
            ('396', 'Provisions pour dépréciation des produits résiduels', 'ACTIF'),
            ('397', 'Provisions pour dépréciation des stocks en cours', 'ACTIF'),
            ('398', 'Provisions pour dépréciation des stocks extérieurs', 'ACTIF'),
            ('399', 'Provisions pour dépréciation des stocks', 'ACTIF'),
            
            # CLASSE 4 : TIERS
            ('40', 'Fournisseurs et comptes rattachés', 'PASSIF'),
            ('401', 'Fournisseurs', 'PASSIF'),
            ('402', 'Fournisseurs - effets à payer', 'PASSIF'),
            ('403', 'Fournisseurs - factures non parvenues', 'PASSIF'),
            ('404', 'Fournisseurs - retenues de garantie', 'PASSIF'),
            ('405', 'Fournisseurs d\'immobilisations', 'PASSIF'),
            ('406', 'Fournisseurs - intérêts courus', 'PASSIF'),
            ('407', 'Fournisseurs - acomptes versés', 'ACTIF'),
            ('408', 'Fournisseurs - factures non reçues', 'PASSIF'),
            ('409', 'Fournisseurs débiteurs', 'ACTIF'),
            ('41', 'Clients et comptes rattachés', 'ACTIF'),
            ('411', 'Clients', 'ACTIF'),
            ('412', 'Clients - effets à recevoir', 'ACTIF'),
            ('413', 'Clients - effets escomptés', 'ACTIF'),
            ('414', 'Clients - créances douteuses', 'ACTIF'),
            ('415', 'Clients - créances litigieuses', 'ACTIF'),
            ('416', 'Clients - factures à établir', 'ACTIF'),
            ('417', 'Clients - intérêts courus', 'ACTIF'),
            ('418', 'Clients - produits non encore facturés', 'ACTIF'),
            ('419', 'Clients créditeurs', 'PASSIF'),
            ('42', 'Personnel et comptes rattachés', 'PASSIF'),
            ('421', 'Personnel - rémunérations dues', 'PASSIF'),
            ('422', 'Personnel - avances et acomptes', 'ACTIF'),
            ('423', 'Personnel - charges à payer', 'PASSIF'),
            ('424', 'Personnel - œuvres sociales', 'PASSIF'),
            ('425', 'Personnel - participation aux résultats', 'PASSIF'),
            ('426', 'Personnel - charges de personnel', 'PASSIF'),
            ('427', 'Personnel - dettes provisionnées', 'PASSIF'),
            ('428', 'Personnel - autres dettes', 'PASSIF'),
            ('429', 'Personnel - avances remboursables', 'ACTIF'),
            ('43', 'Organismes sociaux et comptes rattachés', 'PASSIF'),
            ('431', 'Sécurité sociale', 'PASSIF'),
            ('432', 'Caisses de retraite', 'PASSIF'),
            ('433', 'Autres organismes sociaux', 'PASSIF'),
            ('434', 'Organismes sociaux - charges à payer', 'PASSIF'),
            ('435', 'Organismes sociaux - dettes provisionnées', 'PASSIF'),
            ('436', 'Organismes sociaux - avances', 'ACTIF'),
            ('437', 'Organismes sociaux - autres dettes', 'PASSIF'),
            ('438', 'Organismes sociaux - charges constatées d\'avance', 'ACTIF'),
            ('439', 'Organismes sociaux - intérêts courus', 'PASSIF'),
            ('44', 'État et collectivités publiques', 'PASSIF'),
            ('441', 'État - impôts sur les bénéfices', 'PASSIF'),
            ('442', 'État - impôts et taxes', 'PASSIF'),
            ('443', 'État - taxes sur le chiffre d\'affaires', 'PASSIF'),
            ('444', 'État - taxes sur les salaires', 'PASSIF'),
            ('445', 'État - TVA', 'PASSIF'),
            ('446', 'État - retenues à la source', 'PASSIF'),
            ('447', 'État - charges à payer', 'PASSIF'),
            ('448', 'État - dettes provisionnées', 'PASSIF'),
            ('449', 'État - avances', 'ACTIF'),
            ('45', 'Groupe et associés', 'ACTIF'),
            ('451', 'Groupe', 'ACTIF'),
            ('452', 'Associés', 'ACTIF'),
            ('453', 'Parties liées', 'ACTIF'),
            ('454', 'Associés - opérations sur le capital', 'PASSIF'),
            ('455', 'Associés - dividendes à payer', 'PASSIF'),
            ('456', 'Associés - comptes courants', 'ACTIF'),
            ('457', 'Associés - opérations en cours', 'ACTIF'),
            ('458', 'Associés - autres opérations', 'ACTIF'),
            ('459', 'Associés - créances douteuses', 'ACTIF'),
            ('46', 'Débiteurs et créditeurs divers', 'ACTIF'),
            ('461', 'Débiteurs divers', 'ACTIF'),
            ('462', 'Créances sur cessions d\'immobilisations', 'ACTIF'),
            ('463', 'Créances sur cessions de valeurs mobilières', 'ACTIF'),
            ('464', 'Dettes diverses', 'PASSIF'),
            ('465', 'Créances diverses', 'ACTIF'),
            ('466', 'Dettes diverses', 'PASSIF'),
            ('467', 'Charges à payer', 'PASSIF'),
            ('468', 'Produits à recevoir', 'ACTIF'),
            ('469', 'Charges constatées d\'avance', 'ACTIF'),
            ('47', 'Comptes de régularisation', 'ACTIF'),
            ('471', 'Charges constatées d\'avance', 'ACTIF'),
            ('472', 'Produits constatés d\'avance', 'PASSIF'),
            ('473', 'Charges à répartir', 'ACTIF'),
            ('474', 'Produits à répartir', 'PASSIF'),
            ('475', 'Charges à payer', 'PASSIF'),
            ('476', 'Produits à recevoir', 'ACTIF'),
            ('477', 'Écarts de conversion - actif', 'ACTIF'),
            ('478', 'Écarts de conversion - passif', 'PASSIF'),
            ('48', 'Comptes de régularisation', 'PASSIF'),
            ('481', 'Charges à répartir', 'ACTIF'),
            ('482', 'Produits à répartir', 'PASSIF'),
            ('486', 'Charges constatées d\'avance', 'ACTIF'),
            ('487', 'Produits constatés d\'avance', 'PASSIF'),
            ('488', 'Comptes de régularisation', 'ACTIF'),
            ('489', 'Comptes de régularisation', 'PASSIF'),
            ('49', 'Provisions pour dépréciation des comptes de tiers', 'ACTIF'),
            ('491', 'Provisions pour dépréciation des clients', 'ACTIF'),
            ('492', 'Provisions pour dépréciation des fournisseurs', 'ACTIF'),
            ('493', 'Provisions pour dépréciation du personnel', 'ACTIF'),
            ('494', 'Provisions pour dépréciation des organismes sociaux', 'ACTIF'),
            ('495', 'Provisions pour dépréciation de l\'État', 'ACTIF'),
            ('496', 'Provisions pour dépréciation des associés', 'ACTIF'),
            ('497', 'Provisions pour dépréciation des débiteurs divers', 'ACTIF'),
            ('498', 'Provisions pour dépréciation des créditeurs divers', 'ACTIF'),
            ('499', 'Provisions pour dépréciation des comptes de tiers', 'ACTIF'),
            
            # CLASSE 5 : TRESORERIE
            ('50', 'Emprunts et dettes à court terme', 'PASSIF'),
            ('501', 'Emprunts à court terme', 'PASSIF'),
            ('502', 'Dettes à court terme', 'PASSIF'),
            ('503', 'Emprunts et dettes en devises', 'PASSIF'),
            ('504', 'Intérêts courus sur emprunts', 'PASSIF'),
            ('505', 'Autres emprunts et dettes', 'PASSIF'),
            ('506', 'Concours bancaires courants', 'PASSIF'),
            ('507', 'Soldes créditeurs de banques', 'PASSIF'),
            ('508', 'Intérêts courus', 'PASSIF'),
            ('509', 'Autres emprunts et dettes', 'PASSIF'),
            ('51', 'Banques', 'ACTIF'),
            ('511', 'Valeurs à l\'encaissement', 'ACTIF'),
            ('512', 'Banques', 'ACTIF'),
            ('513', 'Instruments de trésorerie', 'ACTIF'),
            ('514', 'Banques - soldes débiteurs', 'ACTIF'),
            ('515', 'Banques - soldes créditeurs', 'PASSIF'),
            ('516', 'Banques - intérêts courus', 'ACTIF'),
            ('517', 'Banques - opérations en devises', 'ACTIF'),
            ('518', 'Banques - autres opérations', 'ACTIF'),
            ('519', 'Banques - provisions', 'ACTIF'),
            ('52', 'Institutions financières', 'ACTIF'),
            ('521', 'Banque', 'ACTIF'),
            ('522', 'Sociétés financières', 'ACTIF'),
            ('523', 'Caisses d\'épargne', 'ACTIF'),
            ('524', 'Autres institutions financières', 'ACTIF'),
            ('525', 'Institutions financières - soldes débiteurs', 'ACTIF'),
            ('526', 'Institutions financières - soldes créditeurs', 'PASSIF'),
            ('527', 'Institutions financières - intérêts courus', 'ACTIF'),
            ('528', 'Institutions financières - opérations en devises', 'ACTIF'),
            ('529', 'Institutions financières - provisions', 'ACTIF'),
            ('53', 'Caisse', 'ACTIF'),
            ('531', 'Caisse', 'ACTIF'),
            ('532', 'Caisse du siège', 'ACTIF'),
            ('533', 'Caisse succursale', 'ACTIF'),
            ('534', 'Caisse agence', 'ACTIF'),
            ('535', 'Caisse magasin', 'ACTIF'),
            ('536', 'Caisse chantier', 'ACTIF'),
            ('537', 'Caisse autre', 'ACTIF'),
            ('538', 'Caisse - provisions', 'ACTIF'),
            ('54', 'Régies d\'avances', 'ACTIF'),
            ('541', 'Régies d\'avances', 'ACTIF'),
            ('542', 'Régies d\'avances - acomptes', 'ACTIF'),
            ('543', 'Régies d\'avances - frais', 'ACTIF'),
            ('544', 'Régies d\'avances - autres', 'ACTIF'),
            ('545', 'Régies d\'avances - soldes', 'ACTIF'),
            ('546', 'Régies d\'avances - intérêts courus', 'ACTIF'),
            ('547', 'Régies d\'avances - opérations en devises', 'ACTIF'),
            ('548', 'Régies d\'avances - provisions', 'ACTIF'),
            ('55', 'Chèques postaux', 'ACTIF'),
            ('551', 'Chèques postaux', 'ACTIF'),
            ('552', 'Chèques postaux - soldes débiteurs', 'ACTIF'),
            ('553', 'Chèques postaux - soldes créditeurs', 'PASSIF'),
            ('554', 'Chèques postaux - intérêts courus', 'ACTIF'),
            ('555', 'Chèques postaux - opérations en devises', 'ACTIF'),
            ('556', 'Chèques postaux - provisions', 'ACTIF'),
            ('56', 'Valeurs à encaisser', 'ACTIF'),
            ('561', 'Chèques à encaisser', 'ACTIF'),
            ('562', 'Effets à encaisser', 'ACTIF'),
            ('563', 'Billets de trésorerie', 'ACTIF'),
            ('564', 'Obligations cautionnées', 'ACTIF'),
            ('565', 'Autres valeurs à encaisser', 'ACTIF'),
            ('566', 'Valeurs à l\'encaissement - intérêts courus', 'ACTIF'),
            ('567', 'Valeurs à l\'encaissement - opérations en devises', 'ACTIF'),
            ('568', 'Valeurs à l\'encaissement - provisions', 'ACTIF'),
            ('57', 'Instruments de trésorerie', 'ACTIF'),
            ('571', 'Caisse', 'ACTIF'),
            ('572', 'Caisse du siège', 'ACTIF'),
            ('573', 'Caisse succursale', 'ACTIF'),
            ('574', 'Caisse agence', 'ACTIF'),
            ('575', 'Caisse magasin', 'ACTIF'),
            ('576', 'Caisse chantier', 'ACTIF'),
            ('577', 'Caisse autre', 'ACTIF'),
            ('578', 'Caisse - provisions', 'ACTIF'),
            ('58', 'Instruments de trésorerie', 'PASSIF'),
            ('581', 'Instruments de trésorerie', 'PASSIF'),
            ('582', 'Instruments de trésorerie - soldes créditeurs', 'PASSIF'),
            ('583', 'Instruments de trésorerie - intérêts courus', 'PASSIF'),
            ('584', 'Instruments de trésorerie - opérations en devises', 'PASSIF'),
            ('585', 'Instruments de trésorerie - provisions', 'PASSIF'),
            ('59', 'Provisions pour dépréciation des comptes de trésorerie', 'ACTIF'),
            ('591', 'Provisions pour dépréciation des banques', 'ACTIF'),
            ('592', 'Provisions pour dépréciation des institutions financières', 'ACTIF'),
            ('593', 'Provisions pour dépréciation de la caisse', 'ACTIF'),
            ('594', 'Provisions pour dépréciation des régies d\'avances', 'ACTIF'),
            ('595', 'Provisions pour dépréciation des chèques postaux', 'ACTIF'),
            ('596', 'Provisions pour dépréciation des valeurs à encaisser', 'ACTIF'),
            ('597', 'Provisions pour dépréciation des instruments de trésorerie', 'ACTIF'),
            ('598', 'Provisions pour dépréciation des comptes de trésorerie', 'ACTIF'),
            ('599', 'Provisions pour dépréciation de la trésorerie', 'ACTIF'),
            
            # CLASSE 6 : CHARGES
            ('60', 'Achats consommés', 'CHARGE'),
            ('601', 'Achats de marchandises', 'CHARGE'),
            ('602', 'Achats de matières premières', 'CHARGE'),
            ('603', 'Achats de fournitures', 'CHARGE'),
            ('604', 'Loyer', 'CHARGE'),
            ('605', 'Salaires', 'CHARGE'),
            ('606', 'Charges diverses', 'CHARGE'),
            ('61', 'Services extérieurs', 'CHARGE'),
            ('611', 'Sous-traitance', 'CHARGE'),
            ('612', 'Redevances de crédit-bail', 'CHARGE'),
            ('613', 'Locations', 'CHARGE'),
            ('614', 'Charges locatives', 'CHARGE'),
            ('615', 'Entretien et réparations', 'CHARGE'),
            ('616', 'Assurances', 'CHARGE'),
            ('617', 'Études et recherches', 'CHARGE'),
            ('618', 'Divers', 'CHARGE'),
            ('62', 'Autres services extérieurs', 'CHARGE'),
            ('621', 'Personnel extérieur', 'CHARGE'),
            ('622', 'Rémunérations d\'intermédiaires', 'CHARGE'),
            ('623', 'Publicité', 'CHARGE'),
            ('624', 'Transports', 'CHARGE'),
            ('625', 'Déplacements', 'CHARGE'),
            ('626', 'Frais postaux', 'CHARGE'),
            ('627', 'Services bancaires', 'CHARGE'),
            ('628', 'Divers', 'CHARGE'),
            ('63', 'Charges de personnel', 'CHARGE'),
            ('631', 'Rémunérations du personnel', 'CHARGE'),
            ('632', 'Charges sociales', 'CHARGE'),
            ('633', 'Indemnités et avantages', 'CHARGE'),
            ('634', 'Cotisations sociales', 'CHARGE'),
            ('635', 'Autres charges de personnel', 'CHARGE'),
            ('636', 'Charges de personnel - intérêts courus', 'CHARGE'),
            ('637', 'Charges de personnel - opérations en devises', 'CHARGE'),
            ('638', 'Charges de personnel - provisions', 'CHARGE'),
            ('64', 'Impôts et taxes', 'CHARGE'),
            ('641', 'Impôts sur les salaires', 'CHARGE'),
            ('642', 'Impôts sur les bénéfices', 'CHARGE'),
            ('643', 'Taxes sur le chiffre d\'affaires', 'CHARGE'),
            ('644', 'Autres impôts et taxes', 'CHARGE'),
            ('645', 'Impôts et taxes - intérêts courus', 'CHARGE'),
            ('646', 'Autres impôts et taxes', 'CHARGE'),
            ('647', 'Impôts et taxes - opérations en devises', 'CHARGE'),
            ('648', 'Impôts et taxes - provisions', 'CHARGE'),
            ('65', 'Autres charges opérationnelles', 'CHARGE'),
            ('651', 'Redevances pour concessions', 'CHARGE'),
            ('652', 'Redevances pour brevets', 'CHARGE'),
            ('653', 'Redevances pour licences', 'CHARGE'),
            ('654', 'Redevances pour marques', 'CHARGE'),
            ('655', 'Autres redevances', 'CHARGE'),
            ('656', 'Pertes sur créances', 'CHARGE'),
            ('657', 'Charges exceptionnelles', 'CHARGE'),
            ('658', 'Autres charges opérationnelles', 'CHARGE'),
            ('66', 'Charges financières', 'CHARGE'),
            ('661', 'Intérêts sur emprunts', 'CHARGE'),
            ('662', 'Pertes sur créances', 'CHARGE'),
            ('663', 'Pertes sur valeurs mobilières', 'CHARGE'),
            ('664', 'Pertes de change', 'CHARGE'),
            ('665', 'Autres charges financières', 'CHARGE'),
            ('666', 'Charges financières - intérêts courus', 'CHARGE'),
            ('667', 'Charges financières - opérations en devises', 'CHARGE'),
            ('668', 'Charges financières - provisions', 'CHARGE'),
            ('67', 'Charges exceptionnelles', 'CHARGE'),
            ('671', 'Pénalités', 'CHARGE'),
            ('672', 'Créances irrécouvrables', 'CHARGE'),
            ('673', 'Charges sur exercices antérieurs', 'CHARGE'),
            ('674', 'VALEURS COMPTABLES DES CESSIONS D\'IMMOBILISATIONS', 'CHARGE'),
            ('675', 'Autres charges exceptionnelles', 'CHARGE'),
            ('676', 'Charges exceptionnelles - intérêts courus', 'CHARGE'),
            ('677', 'Charges exceptionnelles - opérations en devises', 'CHARGE'),
            ('678', 'Charges exceptionnelles - provisions', 'CHARGE'),
            ('68', 'Dotations aux amortissements et provisions', 'CHARGE'),
            ('681', 'Dotations aux amortissements', 'CHARGE'),
            ('682', 'Dotations aux provisions', 'CHARGE'),
            ('683', 'Dotations aux amortissements - intérêts courus', 'CHARGE'),
            ('684', 'Dotations aux amortissements - opérations en devises', 'CHARGE'),
            ('685', 'Dotations aux amortissements - provisions', 'CHARGE'),
            ('686', 'Dotations aux provisions - intérêts courus', 'CHARGE'),
            ('687', 'Dotations aux provisions - opérations en devises', 'CHARGE'),
            ('688', 'Dotations aux provisions - provisions', 'CHARGE'),
            ('69', 'Participation des salariés', 'CHARGE'),
            ('691', 'Participation aux résultats', 'CHARGE'),
            ('692', 'Intéressement', 'CHARGE'),
            ('693', 'Plan d\'épargne d\'entreprise', 'CHARGE'),
            ('694', 'Autres participations', 'CHARGE'),
            ('695', 'Participation - intérêts courus', 'CHARGE'),
            ('696', 'Participation - opérations en devises', 'CHARGE'),
            ('697', 'Participation - provisions', 'CHARGE'),
            ('698', 'Participation - autres charges', 'CHARGE'),
            ('699', 'Participation - charges exceptionnelles', 'CHARGE'),
            
            # CLASSE 7 : PRODUITS
            ('70', 'Ventes de produits', 'PRODUIT'),
            ('701', 'Ventes de marchandises', 'PRODUIT'),
            ('702', 'Ventes de services', 'PRODUIT'),
            ('703', 'Revenus divers', 'PRODUIT'),
            ('704', 'Travaux', 'PRODUIT'),
            ('705', 'Études', 'PRODUIT'),
            ('706', 'Prestations de services', 'PRODUIT'),
            ('707', 'Produits accessoires', 'PRODUIT'),
            ('71', 'Production stockée', 'PRODUIT'),
            ('711', 'Variation des stocks de produits finis', 'PRODUIT'),
            ('712', 'Variation des stocks de produits en cours', 'PRODUIT'),
            ('713', 'Variation des stocks de produits intermédiaires', 'PRODUIT'),
            ('714', 'Variation des stocks de matières premières', 'PRODUIT'),
            ('715', 'Variation des stocks de fournitures', 'PRODUIT'),
            ('716', 'Variation des stocks de marchandises', 'PRODUIT'),
            ('717', 'Variation des stocks - intérêts courus', 'PRODUIT'),
            ('718', 'Variation des stocks - opérations en devises', 'PRODUIT'),
            ('719', 'Variation des stocks - provisions', 'PRODUIT'),
            ('72', 'Production immobilisée', 'PRODUIT'),
            ('721', 'Production immobilisée d\'immobilisations corporelles', 'PRODUIT'),
            ('722', 'Production immobilisée d\'immobilisations incorporelles', 'PRODUIT'),
            ('723', 'Production immobilisée de stocks', 'PRODUIT'),
            ('724', 'Production immobilisée - intérêts courus', 'PRODUIT'),
            ('725', 'Production immobilisée - opérations en devises', 'PRODUIT'),
            ('726', 'Production immobilisée - provisions', 'PRODUIT'),
            ('73', 'Produits nets sur cessions', 'PRODUIT'),
            ('731', 'Produits de cession d\'immobilisations', 'PRODUIT'),
            ('732', 'Produits de cession de valeurs mobilières', 'PRODUIT'),
            ('733', 'Produits de cession de stocks', 'PRODUIT'),
            ('734', 'Produits de cession - intérêts courus', 'PRODUIT'),
            ('735', 'Produits de cession - opérations en devises', 'PRODUIT'),
            ('736', 'Produits de cession - provisions', 'PRODUIT'),
            ('74', 'Subventions d\'exploitation', 'PRODUIT'),
            ('741', 'Subventions d\'exploitation', 'PRODUIT'),
            ('742', 'Subventions d\'équipement', 'PRODUIT'),
            ('743', 'Autres subventions', 'PRODUIT'),
            ('744', 'Subventions - intérêts courus', 'PRODUIT'),
            ('745', 'Subventions - opérations en devises', 'PRODUIT'),
            ('746', 'Subventions - provisions', 'PRODUIT'),
            ('75', 'Autres produits', 'PRODUIT'),
            ('751', 'Revenus financiers', 'PRODUIT'),
            ('752', 'Gains de change', 'PRODUIT'),
            ('753', 'Revenus des valeurs mobilières', 'PRODUIT'),
            ('754', 'Autres produits financiers', 'PRODUIT'),
            ('755', 'Produits exceptionnels', 'PRODUIT'),
            ('756', 'Autres produits - intérêts courus', 'PRODUIT'),
            ('757', 'Autres produits - opérations en devises', 'PRODUIT'),
            ('758', 'Autres produits - provisions', 'PRODUIT'),
            ('76', 'Produits financiers', 'PRODUIT'),
            ('761', 'Intérêts sur prêts', 'PRODUIT'),
            ('762', 'Revenus de valeurs mobilières', 'PRODUIT'),
            ('763', 'Gains de change', 'PRODUIT'),
            ('764', 'Autres produits financiers', 'PRODUIT'),
            ('765', 'Produits financiers - intérêts courus', 'PRODUIT'),
            ('766', 'Produits financiers - opérations en devises', 'PRODUIT'),
            ('767', 'Produits financiers - provisions', 'PRODUIT'),
            ('77', 'Produits exceptionnels', 'PRODUIT'),
            ('771', 'Produits de cession', 'PRODUIT'),
            ('772', 'Indemnités', 'PRODUIT'),
            ('773', 'Produits sur exercices antérieurs', 'PRODUIT'),
            ('774', 'PRODUITS DES CESSIONS D\'IMMOBILISATIONS', 'PRODUIT'),
            ('775', 'Autres produits exceptionnels', 'PRODUIT'),
            ('776', 'Produits exceptionnels - intérêts courus', 'PRODUIT'),
            ('777', 'Produits exceptionnels - opérations en devises', 'PRODUIT'),
            ('778', 'Produits exceptionnels - provisions', 'PRODUIT'),
            ('78', 'Reprises sur amortissements et provisions', 'PRODUIT'),
            ('781', 'Reprises sur amortissements', 'PRODUIT'),
            ('782', 'Reprises sur provisions', 'PRODUIT'),
            ('783', 'Reprises - intérêts courus', 'PRODUIT'),
            ('784', 'Reprises - opérations en devises', 'PRODUIT'),
            ('785', 'Reprises - provisions', 'PRODUIT'),
            ('786', 'Reprises sur provisions - intérêts courus', 'PRODUIT'),
            ('787', 'Reprises sur provisions - opérations en devises', 'PRODUIT'),
            ('788', 'Reprises sur provisions - provisions', 'PRODUIT'),
            ('79', 'Transferts de charges', 'PRODUIT'),
            ('791', 'Transferts de charges d\'exploitation', 'PRODUIT'),
            ('792', 'Transferts de charges financières', 'PRODUIT'),
            ('793', 'Transferts de charges exceptionnelles', 'PRODUIT'),
            ('794', 'Transferts - intérêts courus', 'PRODUIT'),
            ('795', 'Transferts - opérations en devises', 'PRODUIT'),
            ('796', 'Transferts - provisions', 'PRODUIT'),
        ]
        
        # Insérer les comptes
        for numero, intitule, type_compte in comptes_syscohada:
            cursor.execute('''
                INSERT IGNORE INTO plans_comptables (numero_compte, intitule, type_compte)
                VALUES (%s, %s, %s)
            ''', (numero, intitule, type_compte))
        
        conn.commit()
        print(f"✓ {len(comptes_syscohada)} comptes SYSCOHADA importés avec succès !")
        
    except Error as e:
        print(f"Erreur de connexion : {e}")
        print("Veuillez vérifier vos paramètres de connexion MySQL dans le script.")
    except Exception as e:
        print(f"Erreur : {e}")
    finally:
        if 'conn' in locals() and conn.is_connected():
            cursor.close()
            conn.close()

if __name__ == '__main__':
    import_syscohada()
